load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "marketPacketHelpers",
    srcs = ["marketPacketHelpers.cpp"],
    hdrs = ["marketPacketHelpers.h", "marketPacketStrings.h"],
    visibility = ["//marketPacketProcessor:__pkg__",
                  "//marketPacketGenerator:__pkg__",
                  "//marketPacketHelpers/test:__pkg__"],
)
