cc_test(
  name = "test",
  size = "small",
  srcs = ["marketPacketGenerator_test.cpp"],
  deps = ["@com_google_googletest//:gtest_main",
          "//marketPacketProcessor:marketPacketProcessor",
          "//marketPacketGenerator:marketPacketGenerator",
        ],
)
