cc_test(
  name = "test",
  size = "small",
  srcs = ["marketPacketHelpers_test.cpp"],
  deps = ["@com_google_googletest//:gtest_main",
          "//marketPacketHelpers:marketPacketHelpers",
        ],
)
