load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "marketPacketProcessor",
    srcs = ["marketPacketProcessor.cpp"],
    hdrs = ["marketPacketProcessor.h"],
    deps = [
        "//marketPacketHelpers:marketPacketHelpers",
    ],
    visibility = ["//visibility:public"
    ],
)
